---
title: "Uppsala Armed Conflict Data"
author: "Ghada Amer"
date: "October 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(knitr)
library(formattable)
library(janitor)
library(readr)
library(dplyr)
library(shiny)
library(devtools)
library(leaflet)
library(RColorBrewer)
library(leaflet.extras)
library(dplyr)
library(scales)

  # Read in original csv file into 
  # data frame called data

data <- read_csv("Data/ged181.csv")
actors_list <- read_csv("Data/actorlist.csv") 

```

```{r Clean Data}

  # In this chunk, I started cleaning the data by selecting
  # the variables I plan to use in my app. I removed all 
  # source-related variables and numeric country code schemes
  # as they are not relevant for the purposes of my project. I 
  # also chose to use the average estimate of total deaths 
  # instead of the lowest or highest estimates to provide more
  # accurate results. I recoded the type of violence values from 
  # a numeric code into value labels. 

clean_data <-
  data %>% 
  select(-contains("source"), -low, -high, -contains("gwno")) %>% 
  rename(total_deaths = best) %>% 
  mutate(type_of_violence = case_when(
        type_of_violence == "1" ~ "State-Based Conflict",
        type_of_violence == "2" ~ "Non-State Conflict",
        type_of_violence == "3" ~ "One-Sided Violence")) 

```

```{r Named Data}

  # Since the names of all the actors in the original
  # dataset were abbreviated, I found a list of 
  # full actor names and joined it to the original
  # data. This improves the readability of the markers
  # in the map and the values in the tables I create. 

actors_list_a <-
  actors_list %>% 
  select("side_a_new_id" = "ActorID", "name_full" = "NameFull")

full_name_a <-
  right_join(actors_list_a, clean_data, by = "side_a_new_id")

actors_list_b <-
  actors_list %>% 
  select("side_b_new_id" = "ActorID", "name_full" = "NameFull")

full_name_both <-
  right_join(actors_list_b, full_name_a, by = "side_b_new_id") %>% 
  select(id,
         "name_full_a" = "name_full.x",
         "name_full_b" = "name_full.y", 
         year, 
         latitude,
         longitude,
         type_of_violence,
         dyad_name,  
         "location" = "where_coordinates",
         country,
         region, 
         total_deaths)


write_rds(full_name_both, "full_name_both.rds")

```

```{r Asia Calculations}

  # Since data for each individual conflict is split
  # into side a vs. side b, I performed the 
  # same grouped calculations for each side 
  # separately then binded the rows together using  
  # similar column names. I counted for the number of 
  # distinct conflicts each actor was engaged in 
  # in each side and selected the top 10 in order to
  # provide a useful overview for users. I also
  # filtered out civilians because they do not
  # represent active actors engaged in violence and
  # only represent victims of one-sided violence.
  # Repeated the following steps for each region. 

asia_actors_a <-
  full_name_both %>%
  filter(region == "Asia", !name_full_a == "Civilians") %>% 
  group_by(name_full_a) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_a", "n")

asia_actors_b <-
  full_name_both %>%
  filter(region == "Asia", !name_full_b == "Civilians") %>% 
  group_by(name_full_b) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_b", "n")

asia_all_actors <-
  bind_rows(asia_actors_a, asia_actors_b) %>% 
  arrange(desc(n)) %>% 
  select("Full Name of Actor", "Number of Distinct Conflicts" = "n") %>% 
  mutate(`Number of Distinct Conflicts` = formatC(`Number of Distinct Conflicts`, big.mark = ",")) %>% 
  head(n = 10)

write_rds(asia_all_actors, "asia_all_actors.rds")

```

```{r Africa Calculations}

  # Repeat of previous calculations for top 10
  # most active actors in African region. Activity of 
  # actor is represented by cumulative involvement in
  # distinct armed conflict events. 

africa_actors_a <-
  full_name_both %>%
  filter(region == "Africa", !name_full_a == "Civilians") %>% 
  group_by(name_full_a) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_a", "n")

africa_actors_b <-
  full_name_both %>%
  filter(region == "Africa", !name_full_b == "Civilians") %>% 
  group_by(name_full_b) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_b", "n")

africa_all_actors <-
  bind_rows(africa_actors_a, africa_actors_b) %>% 
  arrange(desc(n)) %>% 
  select("Full Name of Actor", "Number of Distinct Conflicts" = "n") %>% 
  mutate(`Number of Distinct Conflicts` = formatC(`Number of Distinct Conflicts`, big.mark = ",")) %>% 
  head(n = 10)

write_rds(africa_all_actors, "africa_all_actors.rds")

```


```{r Europe Calculations}

 # Repeat of previous calculations for top 10
  # most active actors in European region. Activity of 
  # actor is represented by cumulative involvement in
  # distinct armed conflict events. 

europe_actors_a <-
  full_name_both %>%
  filter(region == "Europe", !name_full_a == "Civilians") %>% 
  group_by(name_full_a) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_a", "n")

europe_actors_b <-
  full_name_both %>%
  filter(region == "Europe", !name_full_b == "Civilians") %>% 
  group_by(name_full_b) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_b", "n")

europe_all_actors <-
  bind_rows(europe_actors_a, europe_actors_b) %>% 
  arrange(desc(n)) %>% 
  select("Full Name of Actor", "Number of Distinct Conflicts" = "n") %>% 
  mutate(`Number of Distinct Conflicts` = formatC(`Number of Distinct Conflicts`, big.mark = ",")) %>% 
  head(n = 10)

write_rds(europe_all_actors, "europe_all_actors.rds")

```


```{r Middle East Calculations}

  # Repeat of previous calculations for top 10
  # most active actors in Middle East region. Activity of 
  # actor is represented by cumulative involvement in
  # distinct armed conflict events. 

mideast_actors_a <-
full_name_both %>%
  filter(region == "Middle East", !name_full_a == "Civilians") %>% 
  group_by(name_full_a) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_a", "n")

mideast_actors_b <-
full_name_both %>%
  filter(region == "Middle East", !name_full_b == "Civilians") %>% 
  group_by(name_full_b) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_b", "n")

mideast_all_actors <-
  bind_rows(mideast_actors_a, mideast_actors_b) %>% 
  arrange(desc(n)) %>% 
  select("Full Name of Actor", "Number of Distinct Conflicts" = "n") %>% 
  mutate(`Number of Distinct Conflicts` = formatC(`Number of Distinct Conflicts`, big.mark = ",")) %>% 
  head(n = 10)


write_rds(mideast_all_actors, "mideast_all_actors.rds")

```


```{r Americas Calculations}

  # Repeat of previous calculations for top 10
  # most active actors in Americas region. Activity of 
  # actor is represented by cumulative involvement in
  # distinct armed conflict events. 

americas_actors_a <-
  full_name_both %>%
  filter(region == "Americas", !name_full_a == "Civilians") %>% 
  group_by(name_full_a) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_a", "n")

americas_actors_b <-
full_name_both %>%
  filter(region == "Americas", !name_full_b == "Civilians") %>% 
  group_by(name_full_b) %>% 
  count() %>% 
  select("Full Name of Actor" = "name_full_b", "n")

americas_all_actors <-
  bind_rows(americas_actors_a, americas_actors_b) %>% 
  arrange(desc(n)) %>% 
  select("Full Name of Actor", "Number of Distinct Conflicts" = "n") %>%
  mutate(`Number of Distinct Conflicts` = formatC(`Number of Distinct Conflicts`, big.mark = ",")) %>% 
  head(n = 10)

write_rds(americas_all_actors, "americas_all_actors.rds")

```

```{r Time Line Data}

  # In this code chunk, I manipulated the data for
  # the line plot that I created directly in the 
  # app page. I chose to create the plot directly on 
  # the app page to be able to quickly run the 
  # app and directly change stylistic features as I see
  # fit. I chose to visualize trends in casualties over 
  # time for each region by different types of violence
  # to give users an in-depth overview of the data. 

deaths_year <-
  clean_data %>% 
  group_by(year, type_of_violence, region) %>% 
  summarize(total_deaths = sum(total_deaths))

write_rds(deaths_year, "plot_deaths_time.rds")

```


```{r Time Calculations}

  # In this code chunk, I calculated various summary
  # statistics of the data. I chose to calculate the 
  # percentage of global conflicts that occured in 
  # each region and the total number of deaths in
  # each region since 1989. These summary statistics
  # will provide a useful overview of the data
  # broken down by region. I will display these 
  # calculations as a table in my app to provide users
  # with more information. 

total_percentages <-
  clean_data %>% 
  mutate(total_conflicts = n_distinct(id)) %>% 
  group_by(region, total_conflicts) %>% 
  count() %>% 
  mutate(percentage_conflicts = n/total_conflicts) %>% 
  ungroup() %>% 
  adorn_pct_formatting(digits = 0) %>% 
  select(region, percentage_conflicts)

total_percentages_2 <-
  clean_data %>%
  group_by(region) %>% 
  summarize(death_per_region = sum(total_deaths)) %>% 
  mutate(death_per_region = formatC(death_per_region, big.mark = ","))

joined_data <- 
  inner_join(total_percentages, total_percentages_2, by = "region") %>% 
  select("Region" = "region", 
         "Percentage of Total Global Conflicts (%)" = "percentage_conflicts", 
         "Total Number of Regional Casualties" = "death_per_region") 


  write_rds(joined_data, "regional_calculations.rds")

```



