---
title: "Armed Conflict Final Project"
author: "Ghada Amer"
date: "October 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

library(tidyverse)
library(stringr)
library(ggplot2)
library(kableExtra)
library(rebus)
library(lubridate)
library(knitr)
library(haven)
library(formattable)
library(janitor)
library(purrr)
library(fs)
library(readr)
library(dplyr)
library(scales)
library(shiny)
library(devtools)
library(maps)
library(mapdata)
library(rvest)
library(magrittr)
library(ggmap)
library(devtools)
library(plotly)
library(countrycode)
library(leaflet)
library(RColorBrewer)
library(leaflet.extras)


data <- read_csv("ged181.csv")


```

```{r Clean Data}

  ## In this chunk, I started cleaning the data by selecting
  ## the variables I plan to use in my app. I removed all 
  ## source-related variables and numeric country code schemes
  ## as they are not relevant for the purposes of my project. I 
  ## also chose to use the average estimate of total deaths 
  ## instead of the lowest or highest estimates to provide more
  ## accurate results. I recoded the type of violence values from 
  ## a numeric code into value labels. 

clean_data <-
  data %>% 
  select(-contains("source"), -low, -high, -contains("gwno")) %>% 
  rename(total_deaths = best) %>% 
  mutate(type_of_violence = case_when(
        type_of_violence == "1" ~ "state-based conflict",
        type_of_violence == "2" ~ "non-state conflict",
        type_of_violence == "3" ~ "one-sided violence")) 

## clean conflict names

```

```{r Line Plot}

  ## In this code chunk, ...

deaths_year <-
  clean_data %>% 
  group_by(year, type_of_violence) %>% 
  summarize(total_deaths = sum(total_deaths))

point <- format_format(big.mark = "," , scientific = FALSE)

deaths_year %>% 
  ggplot(aes(x = year, y = total_deaths, colour = type_of_violence)) +
  geom_line()  +
  geom_point(alpha = 0.8, size = 2) + 
  scale_y_continuous(labels = point) + 
  theme_dark() + 
      labs(title = "Annual Deaths Over Time (1989-2017)",
           subtitle = "by Type of Violence",
           x = "Year",
           y = "Number of Deaths",
           color = "Type of Violence") + 
      theme(title = element_text(size = 14, face = "bold"),
            legend.text = element_text(size = 12, colour = "black"),
            panel.background = element_rect(fill = "black"),
            legend.key = element_rect(fill = "white"),
            legend.title = element_text(face = "bold", size = 12),
            legend.justification = c("right", "top"),
            legend.position = "right",
            axis.title.x = element_text(size = 14, vjust = -0.4), 
            axis.title.y = element_text(size = 14, vjust = 0.4)) +
      scale_color_manual("Type of Violence", values = c("state-based conflict" = "orange", 
                                                     "non-state conflict" = "darkred", 
                                                     "one-sided violence" = "lightpink"))

## make legend elements capitalized

```


```{r}

total_percentages <-
  clean_data %>% 
  mutate(total_conflicts = n_distinct(id)) %>% 
  group_by(region, total_conflicts) %>% 
  count() %>% 
  mutate(percentage_conflicts = n/total_conflicts*100) %>% 
  ungroup() %>% 
  select(region, percentage_conflicts)

total_percentages_2 <-
  clean_data %>%
  group_by(region) %>% 
  summarize(death_per_region = sum(total_deaths))

joined_data <- inner_join(total_percentages, total_percentages_2, by = "region")

```



```{r Leaflet Map}

map_data <-
  clean_data %>% 
  distinct(id, .keep_all = TRUE)

one_sided_con <-
  map_data %>% 
  filter(type_of_violence == "one-sided violence")

non_state_con <-
  map_data %>% 
  filter(type_of_violence == "non-state conflict")

state_con <-
  map_data %>% 
  filter(type_of_violence == "state-based conflict")

red_icon <- makeIcon(
  iconUrl = "http://icons.iconarchive.com/icons/paomedia/small-n-flat/24/map-marker-icon.png",
  iconWidth = 24, iconHeight = 26,
  iconAnchorX = 22, iconAnchorY = 94,
  shadowUrl = "http://leafletjs.com/examples/custom-icons/leaf-shadow.png",
  shadowWidth = 50, shadowHeight = 64,
  shadowAnchorX = 4, shadowAnchorY = 62) 
  
# icon = red_icon
 
violence_palette <- 
   colorFactor(palette = "Reds", 
               levels = c("state-based conflict", 
                          "non-state conflict",
                          "one-sided violence"))



## add searchable codebook for abbreviations
## fix labels and popup (add bold)


```

```{r}
map <- 
leaflet(options = leafletOptions(minZoom = 2)) %>% 
  addProviderTiles("CartoDB.DarkMatter", group = "Black and White Political Boundaries Map") %>% 
  setMaxBounds(lng1 = 180 , lat1 = 90, lng2 = -180, lat2 = -90) %>% 
  addCircleMarkers(lng = one_sided_con$longitude, lat = one_sided_con$latitude,
                   group = "One-Sided Conflict",
             color = violence_palette(map_data$type_of_violence),
             radius = 5, 
             popup = paste0("The actors involved in the conflict are: ",one_sided_con$dyad_name, "."," ",
                            "The conflict started in ", one_sided_con$year, ".", " ",
                            "It consisted of ",  one_sided_con$type_of_violence, "."," ",
                            "Total number of deaths: ", one_sided_con$total_deaths," ", "."),
             label = one_sided_con$dyad_name,
             clusterOptions = markerClusterOptions(),
             labelOptions = labelOptions(noHide = T, 
                                         textsize = "10px", 
                                         direction = "bottom")) %>% 
    addCircleMarkers(lng = non_state_con$longitude, lat = non_state_con$latitude,
                     group = "Non-State Conflict",
             color = violence_palette(non_state_con$type_of_violence),
             radius = 5, 
             popup = paste0("The actors involved in the conflict are: ", non_state_con$dyad_name, "."," ",
                            "The conflict started in ", non_state_con$year, ".", " ",
                            "It consisted of ",  non_state_con$type_of_violence, "."," ",
                            "Total number of deaths: ", non_state_con$total_deaths," ", "."),
             popupOptions = popupOptions(direction = "auto"),
             label = non_state_con$dyad_name,
             clusterOptions = markerClusterOptions(),
             labelOptions = labelOptions(noHide = T, 
                                         textsize = "10px", 
                                         direction = "auto",
                                         opacity = 0.75,
                                         interactive = TRUE )) %>% 
    addCircleMarkers(lng = state_con$longitude, lat = state_con$latitude,
                     group = "State-Based Conflict",
             color = violence_palette(state_con$type_of_violence),
             radius = 5, 
             popup = paste0("The actors involved in the conflict are: ", state_con$dyad_name, "."," ",
                            "The conflict started in ", state_con$year, ".", " ",
                            "It consisted of ",  state_con$type_of_violence, "."," ",
                            "Total number of deaths: ", state_con$total_deaths," ", "."),
             label = state_con$dyad_name,
             clusterOptions = markerClusterOptions(),
             labelOptions = labelOptions(noHide = T, 
                                         textsize = "10px", 
                                         direction = "bottom")) %>% 
  addLegend(pal = violence_palette,
                   values = c("state-based conflict","non-state conflict","one-sided violence" ),
                   opacity = 0.7,
                   title = "Type of Violence",
                   position = "bottomright") %>% 
  addSearchFeatures(targetGroups = c('One-Sided Conflict', 
                      'Non-State Conflict', 
                      'State-Based Conflict')) %>% 
  addSearchOSM() %>%  
  addResetMapButton()

map %>% 
  addProviderTiles("Wikimedia", group = "Coloured Political Boundaries Map") %>% 
  addProviderTiles("Esri.WorldImagery", group = "Coloured Physical Map") %>% 
  addProviderTiles("CartoDB.DarkMatter", group = "Black and White Political Boundaries Map") %>% 
  addLayersControl(baseGroups = c("Black and White Political Boundaries Map", 
                                  "Coloured Political Boundaries Map",
                                  "Coloured Physical Map"),
                   overlayGroups = c("One-Sided Conflict", 
                      "Non-State Conflict", 
                      "State-Based Conflict")) 

## fix provider tiles


```




