---
title: "Armed Conflict Final Project"
author: "Ghada Amer"
date: "October 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(knitr)
library(formattable)
library(janitor)
library(readr)
library(dplyr)
library(shiny)
library(devtools)
library(leaflet)
library(RColorBrewer)
library(leaflet.extras)
library(dplyr)

  ## Read in original csv file into 
  ## data frame called data

data <- read_csv("Data/ged181.csv")
actors_list <- read_csv("actorlist.csv") 

```

```{r Clean Data}

  ## In this chunk, I started cleaning the data by selecting
  ## the variables I plan to use in my app. I removed all 
  ## source-related variables and numeric country code schemes
  ## as they are not relevant for the purposes of my project. I 
  ## also chose to use the average estimate of total deaths 
  ## instead of the lowest or highest estimates to provide more
  ## accurate results. I recoded the type of violence values from 
  ## a numeric code into value labels. 


  
clean_data <-
  data %>% 
  select(-contains("source"), -low, -high, -contains("gwno")) %>% 
  rename(total_deaths = best) %>% 
  mutate(type_of_violence = case_when(
        type_of_violence == "1" ~ "State-Based Conflict",
        type_of_violence == "2" ~ "Non-State Conflict",
        type_of_violence == "3" ~ "One-Sided Violence")) 
  
 
  

```

```{r}

actors_list_a <-
  actors_list %>% 
  select("side_a_new_id" = "ActorID", "name_full" = "NameFull")

full_name_a <-
  right_join(actors_list_a, clean_data, by = "side_a_new_id")

actors_list_b <-
  actors_list %>% 
  select("side_b_new_id" = "ActorID", "name_full" = "NameFull")

full_name_b <-
  right_join(actors_list_b, full_name_a, by = "side_b_new_id")

clean_data_2 <-
  full_name_b %>% 
  unite("full_conflict_name", c("name_full.x","name_full.y"), sep = " vs. ")

```

```{r Line Plot}

  ## In this code chunk, I created a line plot of
  ## total deaths over time faceted by region and 
  ## coloured by type of violence. To do this, I 
  ## grouped the data by year, type of violence and 
  ## region then calculated the sums of the groups.
  ## I chose to use a line plot to better display
  ## trends over time. I also added stylistic features 
  ## to the plot to improve its appearance and readability.

deaths_year <-
  clean_data %>% 
  group_by(year, type_of_violence, region) %>% 
  summarize(total_deaths = sum(total_deaths)) 


deaths_year %>% 
  ggplot(aes(x = year, y = total_deaths, colour = type_of_violence)) +
  geom_line()  +
  geom_point(alpha = 0.8, size = 2) + 
  scale_y_continuous(labels = point) + 
  theme_dark() + 
      labs(title = "Annual Deaths Over Time (1989-2017)",
           subtitle = "by Type of Violence",
           x = "Year",
           y = "Number of Deaths",
           color = "Type of Violence") + 
      theme(title = element_text(size = 14, face = "bold"),
            legend.text = element_text(size = 12, colour = "black"),
            panel.background = element_rect(fill = "black"),
            legend.key = element_rect(fill = "white"),
            legend.title = element_text(face = "bold", size = 12),
            legend.justification = c("right", "top"),
            legend.position = "right",
            axis.title.x = element_text(size = 14, vjust = -0.4), 
            axis.title.y = element_text(size = 14, vjust = 0.4)) +
      scale_color_manual("Type of Violence", values = c("State-Based Conflict" = "orange", 
                                                     "Non-State Conflict" = "darkred", 
                                                     "One-Sided Violence" = "lightpink"))


write_rds(deaths_year, "plot_deaths_time.rds")

```


```{r Calculations}

  ## In this code chunk, I calculated various summary
  ## statistics of the data. I chose to calculate the 
  ## percentage of global conflicts that occured in 
  ## each region and the total number of deaths in
  ## each region since 1989. I will display these 
  ## calculations as a table in my app to provide users
  ## with more information. 

total_percentages <-
  clean_data %>% 
  mutate(total_conflicts = n_distinct(id)) %>% 
  group_by(region, total_conflicts) %>% 
  count() %>% 
  mutate(percentage_conflicts = n/total_conflicts) %>% 
  ungroup() %>% 
  adorn_pct_formatting(digits = 0) %>% 
  select(region, percentage_conflicts)

total_percentages_2 <-
  clean_data %>%
  group_by(region) %>% 
  summarize(death_per_region = sum(total_deaths))

joined_data <- 
  inner_join(total_percentages, total_percentages_2, by = "region") %>% 
  select("Region" = "region", 
         "Percentage of Total Global Conflicts (%)" = "percentage_conflicts", 
         "Total Number of Regional Casualties" = "death_per_region")


  write_rds(joined_data, "regional_calculations.rds")

```

```{r Leaflet Map Calculations}

  ## In this code chunk, I created some objects that I 
  ## will need in my leaflet map. I split up my data into
  ## groups of violence types that will later be integrated
  ## into my map to allow the user to toggle between different
  ## violence categories. I also created a colour palette
  ## for these groups that will later be integrated into my map.
  
map_data <-
  clean_data_2 %>% 
  distinct(id, .keep_all = TRUE)

one_sided_con <-
  map_data %>% 
  filter(type_of_violence == "One-Sided Violence")

non_state_con <-
  map_data %>% 
  filter(type_of_violence == "Non-State Conflict")

state_con <-
  map_data %>% 
  filter(type_of_violence == "State-Based Conflict")
  
 
violence_palette <- 
   colorFactor(palette = "Reds", 
               levels = c("State-Based Conflict", 
                          "Non-State Conflict",
                          "One-Sided Violence"))
```

```{r Leaflet Map}

  ## In this code chunk, I created a leaflet map. I found
  ## a geo-referenced dataset that contained longitude and
  ## latitude information which I could use to plot markers.
  ## I added circle markers in three layers for each group.
  ## I also added base map in three layers to allow the user
  ## to toggle between different map types for 
  ## visualization purposes. I chose a black and white map to
  ## be the default map for contrast with the coloured markers.
  ## I also coloured the circle markers with the palette created
  ## above to represent events by type of violence. I added
  ## labels that automatically display and popups that must be
  ## clicked for extra information.

map <- 
leaflet(options = leafletOptions(minZoom = 2)) %>% 
  addProviderTiles("CartoDB.DarkMatter", 
                   group = "Black and White Political Boundaries Map") %>% 
  setMaxBounds(lng1 = 180 ,
               lat1 = 90, 
               lng2 = -180, 
               lat2 = -90) %>% 
  addCircleMarkers(lng = one_sided_con$longitude, 
                   lat = one_sided_con$latitude,
                   group = "One-Sided Conflict",
             color = violence_palette(map_data$type_of_violence),
             radius = 5, 
             popup = paste0("The actors involved in the conflict are: ",one_sided_con$full_conflict_name, "."," ",
                            "The conflict started in ", one_sided_con$year, ".", " ",
                            "It consisted of ",  one_sided_con$type_of_violence, "."," ",
                            "Total number of deaths: ", one_sided_con$total_deaths," ", "."),
             label = one_sided_con$full_conflict_name,
             clusterOptions = markerClusterOptions(),
             labelOptions = labelOptions(noHide = T, 
                                         textsize = "10px", 
                                         direction = "bottom")) %>% 
    addCircleMarkers(lng = non_state_con$longitude, 
                     lat = non_state_con$latitude,
                     group = "Non-State Conflict",
             color = violence_palette(non_state_con$type_of_violence),
             radius = 5, 
             popup = paste0("The actors involved in the conflict are: ", non_state_con$full_conflict_name, "."," ",
                            "The conflict started in ", non_state_con$year, ".", " ",
                            "It consisted of ",  non_state_con$type_of_violence, "."," ",
                            "Total number of deaths: ", non_state_con$total_deaths," ", "."),
             popupOptions = popupOptions(direction = "auto"),
             label = non_state_con$full_conflict_name,
             clusterOptions = markerClusterOptions(),
             labelOptions = labelOptions(noHide = T, 
                                         textsize = "10px", 
                                         direction = "auto",
                                         opacity = 0.75,
                                         interactive = TRUE )) %>% 
    addCircleMarkers(lng = state_con$longitude,
                     lat = state_con$latitude,
                     group = "State-Based Conflict",
             color = violence_palette(state_con$type_of_violence),
             radius = 5, 
             popup = paste0("The actors involved in the conflict are: ", state_con$full_conflict_name, "."," ",
                            "The conflict started in ", state_con$year, ".", " ",
                            "It consisted of ",  state_con$type_of_violence, "."," ",
                            "Total number of deaths: ", state_con$total_deaths," ", "."),
             label = state_con$full_conflict_name,
             clusterOptions = markerClusterOptions(),
             labelOptions = labelOptions(noHide = T, 
                                         textsize = "10px", 
                                         direction = "bottom")) %>% 
  addLegend(pal = violence_palette,
                   values = c("State-Based Conflict",
                              "Non-State conflict",
                              "One-Sided Violence" ),
                   opacity = 0.7,
                   title = "Type of Violence",
                   position = "bottomright") %>% 
  addSearchFeatures(targetGroups = 
                      c('One-Sided Violence', 
                      'Non-State Conflict', 
                      'State-Based Conflict')) %>% 
  addSearchOSM() %>%  
  addResetMapButton()

map<-
  map %>% 
  addProviderTiles("Wikimedia", 
                   group = "Coloured Political Boundaries Map") %>% 
  addProviderTiles("Esri.WorldImagery",
                   group = "Coloured Physical Map") %>% 
  addProviderTiles("CartoDB.DarkMatter", 
                   group = "Black and White Political Boundaries Map") %>% 
  addLayersControl(baseGroups = c("Black and White Political Boundaries Map", 
                                  "Coloured Political Boundaries Map",
                                  "Coloured Physical Map"),
                   overlayGroups = 
                     c("One-Sided Violence", 
                      "Non-State Conflict", 
                      "State-Based Conflict")) 


write_rds(map, "map_variable.rds")

```
